verb1 = input("give verb")
print("One way kids keep physically fit is through %s" % verb1)
noun = input ("Give noun")
print("When they are on a sports team they adopt a %s lifestyle" % noun)
print("So, by _______ in sports kids prevent health risks like _______")
print("We have an epidemic of ______ in this country, and ______ is one of the best ways for kids to incorporate excerise om their lives")
print("Obesity is another health risks sports helps prevents")
print("_____ teaches the need for regular physical activity.")
print("It shows them staying healthy does not have to be _____")
print("Sports keep kids engaged in school.")
print("Children who participate in sports have increased educational aspirations closer ties to ______, and increased occupational aspirations in youth ")
print("Most schools require student athletes to maintain a 2.0 GPA or higher in order to be eligible to _____ sports.")